FROM python:3.10.12-slim

WORKDIR /app_flask
COPY requirements.txt /app_flask/requirements.txt
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r /app_flask/requirements.txt

COPY flask_app.py /app_flask/flask_app.py
COPY templates /app_flask/templates
COPY static /app_flask/static

ENV FLASK_APP=flask_app.py

EXPOSE 8080
# Run Flask when the container starts
CMD flask run --host 0.0.0.0 --port $PORT

